# Generated by Django 4.2.1 on 2023-06-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_gear_rent', '0013_alter_product_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipoprod',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
