# Generated by Django 4.2.1 on 2023-06-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_gear_rent', '0014_product_tipoprod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='codigo',
        ),
    ]
