# Generated by Django 4.2.1 on 2023-06-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_gear_rent', '0015_remove_product_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoprod', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('oferta', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
