# Generated by Django 4.2.1 on 2023-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_gear_rent', '0019_alter_product_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oferta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
